# Dockerfile.backend
FROM python:3.8-slim-buster

WORKDIR /app/backend

# Install the required system packages
RUN apt-get update && apt-get install -y gcc pkg-config libmariadb-dev

# Copy requirements and install Python dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the application code
COPY RideTunes/rideTunes .

# Directly specify the CMD to run your application
CMD exec gunicorn rideTunes.wsgi:application --bind 0.0.0.0:8080 --timeout 120
