apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2023-11-17T00:48:55Z","generation":4,"labels":{"app":"sharetunezios","environment":"production"},"name":"sharetunezios","namespace":"default","resourceVersion":"359016","uid":"6ebf8a9b-8435-4c57-b591-86fb6c0760e5"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"sharetunezios","environment":"production"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"sharetunezios","environment":"production"}},"spec":{"containers":[{"env":[{"name":"USE_CLOUD_RUN","valueFrom":{"configMapKeyRef":{"key":"USE_CLOUD_RUN","name":"sharetunezios-config-iwor"}}},{"name":"SPOTIFY_KEY","valueFrom":{"configMapKeyRef":{"key":"SPOTIFY_KEY","name":"sharetunezios-config-iwor"}}},{"name":"SPOTIFY_SECRET","valueFrom":{"configMapKeyRef":{"key":"SPOTIFY_SECRET","name":"sharetunezios-config-iwor"}}},{"name":"GOOGLE_KEY","valueFrom":{"configMapKeyRef":{"key":"GOOGLE_KEY","name":"sharetunezios-config-iwor"}}},{"name":"GOOGLE_SECRET","valueFrom":{"configMapKeyRef":{"key":"GOOGLE_SECRET","name":"sharetunezios-config-iwor"}}},{"name":"DJANGO_SECRET_KEY","valueFrom":{"configMapKeyRef":{"key":"DJANGO_SECRET_KEY","name":"sharetunezios-config-iwor"}}},{"name":"DB_PORT","valueFrom":{"configMapKeyRef":{"key":"DB_PORT","name":"sharetunezios-config-iwor"}}},{"name":"DB_NAME","valueFrom":{"configMapKeyRef":{"key":"DB_NAME","name":"sharetunezios-config-iwor"}}},{"name":"DB_USER","valueFrom":{"configMapKeyRef":{"key":"DB_USER","name":"sharetunezios-config-iwor"}}},{"name":"DB_PASSWORD","valueFrom":{"configMapKeyRef":{"key":"DB_PASSWORD","name":"sharetunezios-config-iwor"}}},{"name":"APPLE_KEY","valueFrom":{"configMapKeyRef":{"key":"APPLE_KEY","name":"sharetunezios-config-iwor"}}},{"name":"APPLE_TEAM_ID","valueFrom":{"configMapKeyRef":{"key":"APPLE_TEAM_ID","name":"sharetunezios-config-iwor"}}},{"name":"DJANGO_DEBUG","valueFrom":{"configMapKeyRef":{"key":"DJANGO_DEBUG","name":"sharetunezios-config-iwor"}}},{"name":"DB_HOST","valueFrom":{"configMapKeyRef":{"key":"DB_HOST","name":"sharetunezios-config-iwor"}}},{"name":"INSTANCE_CONNECTION_NAME","valueFrom":{"configMapKeyRef":{"key":"INSTANCE_CONNECTION_NAME","name":"sharetunezios-config-iwor"}}},{"name":"APPLE_SECRET","valueFrom":{"configMapKeyRef":{"key":"APPLE_SECRET","name":"sharetunezios-config-iwor"}}},{"name":"CELERY_BROKER_URL","valueFrom":{"configMapKeyRef":{"key":"CELERY_BROKER_URL","name":"sharetunezios-config-iwor"}}}],"image":"gcr.io/virtual-cairn-324406/sharetunezios-backend@sha256:35cad6e7bd43c7a67e56672bc68adea3b3f38f061ee0752bef124757f8818184","imagePullPolicy":"IfNotPresent","name":"sharetunezios-backend-sha256-1","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/secrets/cloudsql","name":"cloudsql-instance-credentials","readOnly":true}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"cloudsql-instance-credentials","secret":{"defaultMode":420,"secretName":"cloudsql-instance-credentials"}}]}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2023-11-17T00:49:45Z","lastUpdateTime":"2023-11-17T00:49:45Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-11-17T00:48:55Z","lastUpdateTime":"2023-11-17T13:34:50Z","message":"ReplicaSet \"sharetunezios-7d4b76557\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":4,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2023-11-17T00:48:55Z"
  generation: 5
  labels:
    app: sharetunezios
    environment: production
  name: sharetunezios
  namespace: default
  resourceVersion: "373744"
  uid: 6ebf8a9b-8435-4c57-b591-86fb6c0760e5
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sharetunezios
      environment: production
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sharetunezios
        environment: production
    spec:
      containers:
      - env:
        - name: USE_CLOUD_RUN
          valueFrom:
            configMapKeyRef:
              key: USE_CLOUD_RUN
              name: sharetunezios-config-iwor
        - name: SPOTIFY_KEY
          valueFrom:
            configMapKeyRef:
              key: SPOTIFY_KEY
              name: sharetunezios-config-iwor
        - name: SPOTIFY_SECRET
          valueFrom:
            configMapKeyRef:
              key: SPOTIFY_SECRET
              name: sharetunezios-config-iwor
        - name: GOOGLE_KEY
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_KEY
              name: sharetunezios-config-iwor
        - name: GOOGLE_SECRET
          valueFrom:
            configMapKeyRef:
              key: GOOGLE_SECRET
              name: sharetunezios-config-iwor
        - name: DJANGO_SECRET_KEY
          valueFrom:
            configMapKeyRef:
              key: DJANGO_SECRET_KEY
              name: sharetunezios-config-iwor
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: sharetunezios-config-iwor
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: sharetunezios-config-iwor
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: sharetunezios-config-iwor
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: DB_PASSWORD
              name: sharetunezios-config-iwor
        - name: APPLE_KEY
          valueFrom:
            configMapKeyRef:
              key: APPLE_KEY
              name: sharetunezios-config-iwor
        - name: APPLE_TEAM_ID
          valueFrom:
            configMapKeyRef:
              key: APPLE_TEAM_ID
              name: sharetunezios-config-iwor
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              key: DJANGO_DEBUG
              name: sharetunezios-config-iwor
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: sharetunezios-config-iwor
        - name: INSTANCE_CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              key: INSTANCE_CONNECTION_NAME
              name: sharetunezios-config-iwor
        - name: APPLE_SECRET
          valueFrom:
            configMapKeyRef:
              key: APPLE_SECRET
              name: sharetunezios-config-iwor
        - name: CELERY_BROKER_URL
          valueFrom:
            configMapKeyRef:
              key: CELERY_BROKER_URL
              name: sharetunezios-config-iwor
        image: gcr.io/virtual-cairn-324406/sharetunezios-backend@sha256:35cad6e7bd43c7a67e56672bc68adea3b3f38f061ee0752bef124757f8818184
        imagePullPolicy: IfNotPresent
        name: sharetunezios-backend-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets/cloudsql
          name: cloudsql-instance-credentials
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-11-17T00:49:45Z"
    lastUpdateTime: "2023-11-17T00:49:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-11-17T00:48:55Z"
    lastUpdateTime: "2023-11-17T13:34:50Z"
    message: ReplicaSet "sharetunezios-7d4b76557" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 5
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
