# Generated by Django 4.1.7 on 2023-05-01 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_userprofile_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('master_playlist_endpoint', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master_playlist_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_shared_playlists', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='shared_playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
