# Generated by Django 4.1.7 on 2023-05-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_sharedplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedplaylist',
            name='master_playlist_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
