# Generated by Django 4.1.7 on 2023-05-19 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.sharedplaylist'),
        ),
    ]
