# Generated by Django 4.1.7 on 2023-05-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_sharedplaylist_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.playlistinvite'),
        ),
    ]
