# Generated by Django 4.1.7 on 2023-10-28 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0010_notification_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('jwt_access_token', models.TextField()),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=music.models.get_expiry_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otcs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
