# Generated by Django 4.1.7 on 2023-11-02 01:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_onetimecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimecode',
            name='jwt_refresh_token',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
