# Generated by Django 4.1.7 on 2024-01-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_onetimecode_jwt_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username_set',
            field=models.BooleanField(default=False),
        ),
    ]
