# Generated by Django 4.1.7 on 2024-01-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_userprofile_username_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='provider_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
