# Generated by Django 4.1.7 on 2024-02-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_userprofile_provider_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedplaylist',
            name='tracks_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
