# Generated by Django 4.1.7 on 2024-03-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_sharedplaylist_tracks_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedplaylist',
            name='tracks_json',
        ),
        migrations.AddField(
            model_name='sharedplaylist',
            name='tracks_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
